In [1]:
ReloadProject('deep_learning')

Path /workspace/external/ added to PYTHON_PATH.
Path /workspace/external/deep_learning added to PYTHON_PATH.


Using TensorFlow backend.


notebook_init.py imported and reloaded
forwarded symbol: Activation
forwarded symbol: Dense
forwarded symbol: Dict
forwarded symbol: InputLayer
forwarded symbol: List
forwarded symbol: Model
forwarded symbol: Sequential
forwarded symbol: Tuple
reloaded: gym
forwarded symbol: gym
reloaded: keras
forwarded symbol: keras
reloaded: q_base
forwarded symbol: q_base


In [2]:
from deep_learning.

In [3]:
dir(a)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [4]:
str(a)

'{}'

In [5]:
np.array([a, a])

array([{}, {}], dtype=object)

In [8]:
a = np.array([[1,2,3],[4,5,6]])

In [7]:
a * np.array([7, 8, 9])

array([[ 7, 16, 27],
       [28, 40, 54]])

In [9]:
for b in a:
    print(b)

[1 2 3]
[4 5 6]


In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a[0]

array([1, 2, 3])

In [14]:
a[0, np.newaxis]

array([[1, 2, 3]])