In [8]:
ReloadProject('deep_learning')

notebook_init.py imported and reloaded
reloaded: a3c_impl
forwarded symbol: a3c_impl
reloaded: base
forwarded symbol: base
reloaded: circular_world_env
forwarded symbol: circular_world_env
reloaded: environment_impl
forwarded symbol: environment_impl
reloaded: guided_environments
forwarded symbol: guided_environments
reloaded: gym
forwarded symbol: gym
reloaded: keras
forwarded symbol: keras
reloaded: layers
forwarded symbol: layers
reloaded: logging
forwarded symbol: logging
reloaded: model_builder
forwarded symbol: model_builder
reloaded: models
forwarded symbol: models
reloaded: numpy
forwarded symbol: numpy
reloaded: numpy_util
forwarded symbol: numpy_util
reloaded: optimizers
forwarded symbol: optimizers
reloaded: policy_impl
forwarded symbol: policy_impl
reloaded: qfunc_impl
forwarded symbol: qfunc_impl
reloaded: runner_extension_impl
forwarded symbol: runner_extension_impl
reloaded: runner_impl
forwarded symbol: runner_impl
reloaded: running_environment
forwarded symbol: running

In [9]:
model = a3c_impl.CreateModel(
    state_shape=(1,),
    action_space_size=3,
    hidden_layer_sizes=(6,6,6),
)

(None, 1)

In [10]:
a3c_impl.A3C(model=model)

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
Use tf.cast instead.


In [12]:
r = numpy.array([ 1., -1.])

In [14]:
r_mask = numpy.array([1, 1])

In [16]:
values = numpy.array([[0.10949473], [0.10949473]])

In [18]:
values * r_mask

array([[0.10949473, 0.10949473],
       [0.10949473, 0.10949473]])

In [19]:
r_mask[np.newaxis, :]

array([[1, 1]])

In [2]:
running_environment.ForceCpuForTheRun()

In [17]:
a = retro.data.merge('../../../roms/contraforce.nes', quiet=False)

Importing ContraForce-Nes
Imported 1 games


In [16]:
env = retro.make(game='ContraForce-Nes')

In [20]:
values.flatten()

array([0.10949473, 0.10949473])

In [12]:
retro.list_games()

AttributeError: module 'retro' has no attribute 'list_games'

In [19]:
from qpylib import running_environment

In [20]:
running_environment.ForceCpuForTheRun()

In [24]:
pipeline = shortcut.ScreenLearningPipeline(gym_env_name='ContraForce', gym_env=env)

[20:01:50] c:\Workspace\git\qpylib\logging.py:44 Using qfunc implementation: DQN_TargetNetwork
[20:01:50] c:\Workspace\git\qpylib\logging.py:44 Using policy implementation: GreedyPolicyWithDecreasingRandomness
[20:01:50] c:\Workspace\git\qpylib\logging.py:44 Using runner implementation: ExperienceReplayRunner


In [25]:
pipeline.Demo()

DependencyNotInstalled: Found neither the ffmpeg nor avconv executables. On OS X, you can install ffmpeg via `brew install ffmpeg`. On most Ubuntu variants, `sudo apt-get install ffmpeg` should do it. On Ubuntu 14.04, however, you'll need to install avconv with `sudo apt-get install libav-tools`.

In [5]:
env.action_space

Discrete(256)

In [4]:
env = gym.make('SuperMarioBros-v0')

In [3]:
import gym_super_mario_bros

In [9]:
gym_super_mario_bros.__doc__

'Registration code of Gym environments in this package.'

In [10]:
env._max_episode_steps

9999999

In [3]:
[a for a in range(10)][-5:]

[5, 6, 7, 8, 9]

In [1]:
a = np.array([1,2,3,4,5])

In [2]:
a[2,3] = 0

IndexError: too many indices for array

In [4]:
a = tempfile.NamedTemporaryFile()

In [3]:
import tempfile

In [5]:
a.name

'C:\\Users\\ChihC\\AppData\\Local\\Temp\\tmpaesvs4c2'

In [5]:
l_input = Input( batch_shape=(None, 5) )
l_dense = Dense(16, activation='relu')(l_input)

out_actions = Dense(3, activation='softmax')(l_dense)
out_value   = Dense(1, activation='linear')(l_dense)

model = keras.Model(inputs=[l_input], outputs=[out_actions, out_value])
model._make_predict_function()	# have to initialize before threading

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
from keras.layers import *

In [12]:
import keras

In [6]:
output_shape = model.layers[-1]

In [7]:
output_shape.output_shape

(None, 1)

In [8]:
output_shape = model.layers[-2]

In [9]:
output_shape.output_shape

(None, 3)

In [10]:
for l in model.layers:
    print(l)

In [11]:
model.predict(np.array([[1,2,3,4,5]]))

[array([[0.38520294, 0.6118986 , 0.00289841]], dtype=float32),
 array([[0.7146762]], dtype=float32)]

In [24]:
np.array([[1,2,3,4,5]]).shape

(1, 5)

In [25]:
running_environment

NameError: name 'running_environment' is not defined

In [15]:
type(tensorflow.train.RMSPropOptimizer(5e-3, decay=.99))

tensorflow.python.training.rmsprop.RMSPropOptimizer

In [13]:
import tensorflow

In [18]:
help(keras.Model.save_weights)

Help on function save_weights in module keras.engine.network:

save_weights(self, filepath, overwrite=True)
    Dumps all layer weights to a HDF5 file.
    
    The weight file has:
        - `layer_names` (attribute), a list of strings
            (ordered names of model layers).
        - For every layer, a `group` named `layer.name`
            - For every such layer group, a group attribute `weight_names`,
                a list of strings
                (ordered names of weights tensor of the layer).
            - For every weight in the layer, a dataset
                storing the weight value, named after the weight tensor.
    
    # Arguments
        filepath: String, path to the file to save the weights to.
        overwrite: Whether to silently overwrite any existing file at the
            target location, or provide the user with a manual prompt.
    
    # Raises
        ImportError: If h5py is not available.



In [23]:
l0 = layers.Input(shape=(3,2))

In [24]:
l1 = layers.Dense(units=2)(l0)

ValueError: Layer dense_5 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.layers.core.Dense'>. Full input: [<keras.layers.core.Dense object at 0x000001CEAC787DA0>]. All inputs to the layer should be tensors.

In [24]:
f = numpy.log(0.5) / 100
(0.05 + (1.0 - 0.05) * numpy.exp(f * 100))

0.525

In [25]:
f = numpy.log(0.5) / 100
(0.05 + (1.0 - 0.05) * numpy.exp(f * 200))

0.2875