In [2]:
ReloadProject('deep_learning')

Path /workspace/external/ added to PYTHON_PATH.
Path /workspace/external/deep_learning added to PYTHON_PATH.


Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


notebook_init.py imported and reloaded
forwarded symbol: A
forwarded symbol: Activation
forwarded symbol: Dense
forwarded symbol: InputLayer
forwarded symbol: Model
forwarded symbol: Sequential
forwarded symbol: T
reloaded: circular_world_env
forwarded symbol: circular_world_env
reloaded: environment_impl
forwarded symbol: environment_impl
reloaded: gym
forwarded symbol: gym
reloaded: keras
forwarded symbol: keras
reloaded: logging
forwarded symbol: logging
reloaded: numpy
forwarded symbol: numpy
reloaded: numpy_util
forwarded symbol: numpy_util
reloaded: optimizers
forwarded symbol: optimizers
reloaded: policy_impl
forwarded symbol: policy_impl
reloaded: q_base
forwarded symbol: q_base
reloaded: qfunc_impl
forwarded symbol: qfunc_impl
reloaded: runner_impl
forwarded symbol: runner_impl


In [25]:
env = environment_impl.GymEnvironment(gym.make('MsPacman-v0'))
env.Reset()
env.TurnOnRendering(True)
for _ in range(100):
    env.TakeRandomAction()

In [3]:
ee = gym.make('MsPacman-v0')

In [5]:
ee.render()

True

In [28]:
env = environment_impl.GymEnvironment(gym.make('MsPacman-v0'))

In [ ]:
for _ in range(10000):
    env._gym_env.render()
    env.TakeRandomAction()

In [81]:
get_ipython()

In [3]:
gym_env = gym.make('CartPole-v1')

In [4]:
gym_env.observation_space

Box(4,)

In [5]:
gym_env.reset()

array([-0.04668168, -0.04442054,  0.03198988, -0.02079956])

In [16]:
aa = gym_env.render(mode='rgb_array')

In [78]:
type(aa)

numpy.ndarray

In [15]:
%matplotlib inline

In [66]:
mm.fit(x, y, batch_size=64, epochs=100, verbose=0)

In [67]:
test_x = np.random.uniform(0, 1, (1, 3))
test_y = mm.predict(test_x)
print(test_x, test_y, f(test_x))

[[0.67037628 0.72736467 0.36100568]] [[1.3387735 1.442457  0.7337395]] [[1.34075257 1.45472934 0.72201136]]


In [48]:
def f(x):
    return x[:,0] + x[:,1]

In [57]:
model = Sequential()
model.add(Dense(units=20, activation='relu', input_dim=2))
model.add(Dense(units=20, activation='relu'))
model.add(Dense(units=20, activation='relu'))
model.add(Dense(units=1))

opt = optimizers.RMSprop(lr=0.00025)
model.compile(loss='mse', optimizer=opt)

In [60]:
x = np.random.uniform(0, 10, (10000, 2))
y = f(x)
model.fit(x, y, batch_size=64, epochs=10, verbose=0)

test_x = np.random.uniform(0, 1, (1, 2))
test_y = model.predict(test_x)
print(test_x, test_y, f(test_x))

[[0.96071863 0.10760231]] [[1.0743402]] [1.06832094]


In [47]:
x[:,0]

array([5.14692809, 0.73262878, 3.1472795 , ..., 6.97974931, 3.98367576,
       6.82874924])

In [24]:
np.random.uniform(0, 1)

0.8649707596300503

In [44]:
np.random.randint(0,3)

2

In [45]:
np.argmax(np.array([[1 , 2, 3]]))

2

In [68]:
np.abs(np.array([[-1, 2]]))

array([[1, 2]])