In [1]:
ReloadProject('deep_learning')

Path /workspace/external/deep_learning added to PYTHON_PATH.


Using TensorFlow backend.


notebook_init.py imported and reloaded
forwarded symbol: Activation
forwarded symbol: Dense
forwarded symbol: Dict
forwarded symbol: InputLayer
forwarded symbol: List
forwarded symbol: Model
forwarded symbol: Sequential
forwarded symbol: Tuple
reloaded: gym
forwarded symbol: gym
reloaded: keras
forwarded symbol: keras
reloaded: openai_wrapper
forwarded symbol: openai_wrapper
reloaded: policy_impl
forwarded symbol: policy_impl
reloaded: q_function_memoization
forwarded symbol: q_function_memoization
reloaded: q_learning
forwarded symbol: q_learning
reloaded: q_learning_impl
forwarded symbol: q_learning_impl
reloaded: q_learning_impl_v2
forwarded symbol: q_learning_impl_v2
reloaded: q_learning_v2
forwarded symbol: q_learning_v2


In [2]:
model = Sequential()
model.add(Dense(6, activation='relu', input_dim=4))
model.add(Dense(6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# model.fit(train_data, one_hot_train_labels, epochs=10, batch_size=32)

In [6]:
l0 = model.layers[0]

In [7]:
l0.input_shape

(None, 4)

In [8]:
l0.output_shape

(None, 6)

In [13]:
model.layers[1].input_shape

(None, 6)

In [44]:
a = l0.weights[0]

In [45]:
help(l0.set_weights)

Help on method set_weights in module keras.engine.base_layer:

set_weights(weights) method of keras.layers.core.Dense instance
    Sets the weights of the layer, from Numpy arrays.
    
    # Arguments
        weights: a list of Numpy arrays. The number
            of arrays and their shape must match
            number of the dimensions of the weights
            of the layer (i.e. it should match the
            output of `get_weights`).
    
    # Raises
        ValueError: If the provided weights list does not match the
            layer's specifications.



In [46]:
type(l0)

keras.layers.core.Dense

In [56]:
aa = np.array(l0.weights[0])

In [71]:
l0.get_weights()[0].size

24

In [69]:
for x in np.array(l0.get_weights()[0]).flat: print(x)

-0.1478414
-0.5456128
0.36180294
-0.3867397
0.6151171
0.33354437
-0.5644657
-0.73246217
0.5517826
0.75709915
0.55597603
-0.5881792
0.18272084
0.03292185
0.3713869
0.5223334
0.36544228
0.443789
0.27010655
-0.3026097
-0.007932663
0.6930001
0.028279066
0.56448746


In [72]:
a = l0.get_weights()[0]

In [73]:
a.flatten()

array([-0.1478414 , -0.5456128 ,  0.36180294, -0.3867397 ,  0.6151171 ,
        0.33354437, -0.5644657 , -0.73246217,  0.5517826 ,  0.75709915,
        0.55597603, -0.5881792 ,  0.18272084,  0.03292185,  0.3713869 ,
        0.5223334 ,  0.36544228,  0.443789  ,  0.27010655, -0.3026097 ,
       -0.00793266,  0.6930001 ,  0.02827907,  0.56448746], dtype=float32)

In [74]:
a

array([[-0.1478414 , -0.5456128 ,  0.36180294, -0.3867397 ,  0.6151171 ,
         0.33354437],
       [-0.5644657 , -0.73246217,  0.5517826 ,  0.75709915,  0.55597603,
        -0.5881792 ],
       [ 0.18272084,  0.03292185,  0.3713869 ,  0.5223334 ,  0.36544228,
         0.443789  ],
       [ 0.27010655, -0.3026097 , -0.00793266,  0.6930001 ,  0.02827907,
         0.56448746]], dtype=float32)

In [76]:
a.flatten().reshape((4, 6))

array([[-0.1478414 , -0.5456128 ,  0.36180294, -0.3867397 ,  0.6151171 ,
         0.33354437],
       [-0.5644657 , -0.73246217,  0.5517826 ,  0.75709915,  0.55597603,
        -0.5881792 ],
       [ 0.18272084,  0.03292185,  0.3713869 ,  0.5223334 ,  0.36544228,
         0.443789  ],
       [ 0.27010655, -0.3026097 , -0.00793266,  0.6930001 ,  0.02827907,
         0.56448746]], dtype=float32)

In [75]:
a.shape

(4, 6)

In [19]:
b = np.array([[3,4, 5], [1,2,3]])

In [28]:
for x in b.flat:
    print(x)

3
4
5
1
2
3


In [29]:
b.flat

In [37]:
c = iter(b)

In [38]:
next(c) = [1,2]

SyntaxError: can't assign to function call (<ipython-input-38-80192ea9e8bc>, line 1)

In [83]:
d = [2,5,4]

In [41]:
np.concatenate([[1,2,3], [4,5,6]])

array([1, 2, 3, 4, 5, 6])

In [89]:
np.average([x for x in d])

3.6666666666666665

In [43]:
a = np.random.rand(2, 4)

In [2]:
np.exp(-2)

0.1353352832366127

In [38]:
a.reshape(4)

array([0.24758063, 0.32835502, 0.24135618, 0.69649496])

In [39]:
Model

keras.engine.training.Model

In [40]:
isinstance(model, Model)

True

In [44]:
a.shape

(2, 4)

In [45]:
a.size

8

In [46]:
np.ndarray

numpy.ndarray

In [4]:
np.random.random()

0.338982697815279

In [48]:
np.array

<function numpy.core.multiarray.array>

In [49]:
np.ndarray

numpy.ndarray

In [52]:
type(np.random.random(size=(5, 2)))

numpy.ndarray

In [54]:
a = range(5)

In [58]:
for b in a: print(b)

0
1
2
3
4


In [59]:
np.max([1,2,3])

3

In [66]:
a = np.array([1,2,3,4,5])

In [68]:
{str(a): 1}

{'[1 2 3 4 5]': 1}

In [64]:
a[:3] = b

In [65]:
a

array([2, 3, 4, 4, 5])