In [69]:
ReloadProject('deep_learning')

notebook_init.py imported and reloaded
forwarded symbol: Activation
forwarded symbol: Dense
forwarded symbol: Dict
forwarded symbol: Input
forwarded symbol: InputLayer
forwarded symbol: List
forwarded symbol: Model
forwarded symbol: Sequential
forwarded symbol: Tuple
reloaded: gym
forwarded symbol: gym
reloaded: keras
forwarded symbol: keras
reloaded: openai_wrapper
forwarded symbol: openai_wrapper
reloaded: q_learning
forwarded symbol: q_learning
reloaded: q_learning_impl
forwarded symbol: q_learning_impl
reloaded: q_learning_impl_v2
forwarded symbol: q_learning_impl_v2
reloaded: q_learning_v2
forwarded symbol: q_learning_v2


In [30]:
model = Sequential()
model.add(Dense(6, activation='relu', input_dim=4))
model.add(Dense(6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# model.fit(train_data, one_hot_train_labels, epochs=10, batch_size=32)

In [70]:
a = [1,23]

In [71]:
a.clear()

In [72]:
a

[]

In [19]:
b

array([0.77996162, 0.57112201, 0.67536716, 0.85322067, 0.29181214])

In [23]:
np.row_stack([np.transpose(a), np.transpose(b)])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [24]:
np.transpose(a)

array([0.35648866, 0.90679722, 0.1984452 , 0.57910397])

In [31]:
model.fit(np.random.rand(1, 4), np.random.rand(1, 1))

Epoch 1/1
1/1 [==============================] - 1s 520ms/step - loss: 14.0207 - acc: 0.0000e+00


In [35]:
np.concatenate((np.random.rand(1, 4).reshape(4), np.random.rand(1, 1).reshape(1)), axis=0)

array([0.83690391, 0.26532925, 0.31448215, 0.21177088, 0.27506416])

In [43]:
a = np.random.rand(2, 4)

In [37]:
a

array([[0.24758063, 0.32835502, 0.24135618, 0.69649496]])

In [38]:
a.reshape(4)

array([0.24758063, 0.32835502, 0.24135618, 0.69649496])

In [39]:
Model

keras.engine.training.Model

In [40]:
isinstance(model, Model)

True

In [44]:
a.shape

(2, 4)

In [45]:
a.size

8

In [46]:
np.ndarray

numpy.ndarray

In [4]:
np.random.random()

0.338982697815279

In [48]:
np.array

<function numpy.core.multiarray.array>

In [49]:
np.ndarray

numpy.ndarray

In [52]:
type(np.random.random(size=(5, 2)))

numpy.ndarray

In [54]:
a = range(5)

In [58]:
for b in a: print(b)

0
1
2
3
4


In [59]:
np.max([1,2,3])

3

In [66]:
a = np.array([1,2,3,4,5])

In [68]:
{str(a): 1}

{'[1 2 3 4 5]': 1}

In [64]:
a[:3] = b

In [65]:
a

array([2, 3, 4, 4, 5])