In [51]:
ReloadProject('deep_learning')

notebook_init.py imported and reloaded
forwarded symbol: Activation
forwarded symbol: Dense
forwarded symbol: Dict
forwarded symbol: InputLayer
forwarded symbol: List
forwarded symbol: Model
forwarded symbol: Sequential
forwarded symbol: Tuple
reloaded: gym
forwarded symbol: gym
reloaded: keras
forwarded symbol: keras
reloaded: model_optimization
forwarded symbol: model_optimization
reloaded: openai_wrapper
forwarded symbol: openai_wrapper
reloaded: policy_impl
forwarded symbol: policy_impl
reloaded: q_function_memoization
forwarded symbol: q_function_memoization
reloaded: q_learning
forwarded symbol: q_learning
reloaded: q_learning_impl
forwarded symbol: q_learning_impl
reloaded: q_learning_impl_v2
forwarded symbol: q_learning_impl_v2
reloaded: q_learning_v2
forwarded symbol: q_learning_v2


In [52]:
model = Sequential()
model.add(Dense(6, activation='relu', input_dim=4))
model.add(Dense(6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [31]:
aa = model_optimization.LayerWeightManager(model.layers[0])

In [32]:
aa.GetWeights()

array([ 0.53980327, -0.62837845, -0.6215627 ,  0.7384007 , -0.25144792,
        0.11380023, -0.40517318, -0.12657589,  0.4743824 ,  0.62035215,
        0.71234345,  0.64350426, -0.3503071 , -0.43894196, -0.2709673 ,
        0.11897528, -0.66504556,  0.57121575,  0.4438156 , -0.00876778,
        0.08285463,  0.5180607 , -0.4271931 ,  0.1357553 ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
      dtype=float32)

In [33]:
aa.SetWeights(np.array(range(50)))

In [34]:
aa.GetWeights()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.], dtype=float32)

In [55]:
bb = model_optimization.ModelWeightManager(model)

In [56]:
bb.GetWeights()

array([ 0.4408946 ,  0.2990836 ,  0.42501223, -0.3964281 ,  0.41178727,
       -0.43523934,  0.07427037,  0.6887671 , -0.3292259 ,  0.68782675,
        0.18409705, -0.39320675, -0.65796995,  0.6311842 , -0.7182722 ,
       -0.21478671,  0.38936698,  0.27595532, -0.37821937, -0.21453387,
       -0.66903037, -0.38640285, -0.22912216,  0.44894135,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.36405236,  0.58702165,  0.23612368,  0.46679956,  0.06125253,
       -0.2024647 ,  0.47349375, -0.5140668 ,  0.40908116, -0.07302344,
       -0.02486277,  0.12140822,  0.47490698, -0.5786246 , -0.6388459 ,
        0.1835748 ,  0.49924546, -0.37001258, -0.14932293,  0.20651263,
       -0.358186  ,  0.36232942, -0.42000532,  0.04982114, -0.7002518 ,
       -0.12165707,  0.16975117, -0.20558488, -0.28086728,  0.6262297 ,
        0.06043911,  0.4987225 ,  0.02621734,  0.16723329,  0.46285552,
        0.18816191,  0.        ,  0.        ,  0.        ,  0.  

In [58]:
bb.SetWeights(np.array(range(200)))

In [59]:
bb.GetWeights()

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.],
      dtype=float32)